### PR TITLE
Pass subparser to delegate fn; use docstring for help text

### PR DESCRIPTION
**Pull request by jake-low**
Moving towards a more modular architecture.

### CODE REVIEW

**Comment by dmtucker** [comment]
Looks like `iteritems` is gone in Python3.
http://stackoverflow.com/questions/10458437/what-is-the-difference-between-dict-items-and-dict-iteritems

**Comment by karth295** [comment]
I feel like the subcommands should each live in their own file. cmd.py should just import the "main" function of every file.

**Comment by dmtucker** [comment]
@karth295 I agree; however, I would consider `help`, `version`, and `hello` exempt since there is nothing below them.

`help` may not be exempt if we want to do something like this:

```
$ yaas help blueprint
```

instead of just 

```
$ yaas help
```

But, since we'll be getting `--help` for free,

```
$ yaas blueprint --help
```

I would vote against that.

**Comment by dmtucker** [comment]
@jake-low Also, I don't hink we need `inspect` here. `subparsers.add_parser(name, help=None)` produces the same results for me.

**Comment by jake-low** [comment]
@dmtucker I just tried what you described; that's false -- `add_parser` doesn't even know about the `fn` otherwise...

**Comment by dmtucker** [comment]
@jake-low What do you mean? Not providing help text should not affect finding the fn... I'll give it another go.

_**Edit:**_ Ok, you're right, I'm trippin'... no idea how that could've worked for me before. Anyways, I still don't think we need `inspect`. Shouldn't `fn.__doc__` suffice?

**Comment by dmtucker** [comment]
Ah, I see `inspect.getdoc()` cleans up a little in case we have long docstrings... should be fine how it is.

**Pull request merged**
