### PR TITLE
Move the Design Doc to the README.

### PR DESCRIPTION
**Pull request by dmtucker**
I added `blueprint template` and changed `cluster create`.

### CODE REVIEW

**Comment by karth295** [comment]
Let's move it to the readme after we finish the design

**Comment by dmtucker** [comment]
Certainly it's not finished, but I think it's good enough to require commits to make changes. I mean, on the wiki, we are making commits anyways just in a separate history :/

**Comment by karth295** [comment]
The doc is missing things like cluster stop/start. At least we should have all the commands we plan to support in v0.1, then make commits if/when we change their output

**Comment by dmtucker** [comment]
I agree. It's also missing things like `services`, `tasks`, etc.
The point is that we should be keeping one history.
Also, the empty README we have now is missing WAY more than this commit is.

**Pull request merged**
